name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
     
      - name: Install
        run: |
          npm install --engine-strict --strict-peer-deps --dry-run
          npm ci

      - name: Lint
        run: |
          npm run prettier:check
          npm run lint

      - name: Build
        run: npm run build
          
      - name: Test
        run: npm run test:coverage
    
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage/lcov-report
          
      - name: Write coverage badge
        uses: action-badges/cobertura-coverage-xml-badges@main
        # if: github.event_name != 'pull_request'
        with:
          badge-branch: badges
          file-name: coverage.svg
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: ./coverage/cobertura-coverage.xml

      - name: Publish package
        if: github.event_name != 'pull_request'
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          strategy: all
          access: public
